services:
  - type: web
    name: anistream-backend
    runtime: node
    rootDir: backend-hono
    buildCommand: yarn && yarn build
    startCommand: yarn start
    plan: free
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
